// Realistic mock intelligence stats for monitored countries, organized by
// filterable category. Values are illustrative estimates for the ATIS
// intelligence platform, not live data.

export interface StatMetric {
  label: string;
  value: string;
  note?: string;
}

export interface CountryStatsProfile {
  agriculture: StatMetric[];
  water: StatMetric[];
  climate: StatMetric[];
  languages: StatMetric[];
  population: StatMetric[];
  economy: StatMetric[];
}

export type StatCategoryKey = keyof CountryStatsProfile;

export const STAT_CATEGORIES: { key: StatCategoryKey; label: string }[] = [
  { key: 'agriculture', label: 'Agriculture' },
  { key: 'water', label: 'Water' },
  { key: 'climate', label: 'Climate' },
  { key: 'languages', label: 'Languages' },
  { key: 'population', label: 'Population' },
  { key: 'economy', label: 'Economy' },
];

export const countryStatsMock: Record<string, CountryStatsProfile> = {
  kenya: {
    agriculture: [
      { label: 'Arable Land', value: '9.8%', note: 'of total land area' },
      { label: 'Agriculture Share of GDP', value: '21.2%' },
      { label: 'Workforce in Agriculture', value: '54%' },
      { label: 'Leading Exports', value: 'Tea, coffee, cut flowers, horticulture' },
      { label: 'Irrigated Cropland', value: '1.2%', note: 'high rain-fed dependency' },
    ],
    water: [
      { label: 'Access to Clean Water', value: '63%', note: 'of population' },
      { label: 'Renewable Water Resources', value: '20.2 km³/yr' },
      { label: 'Major Basins', value: 'Lake Victoria, Tana River' },
      { label: 'Water Stress Level', value: 'Medium–High' },
      { label: 'Hydropower Share of Grid', value: '32%' },
    ],
    climate: [
      { label: 'Climate Zone', value: 'Tropical, arid highlands' },
      { label: 'Avg. Annual Temperature', value: '24°C (75°F)' },
      { label: 'Annual Rainfall', value: '680 mm' },
      { label: 'Dominant Climate Risk', value: 'Drought cycles (3–5 yr)' },
      { label: 'Rainy Seasons', value: 'Mar–May, Oct–Dec' },
    ],
    languages: [
      { label: 'Official Languages', value: 'Swahili, English' },
      { label: 'Widely Spoken', value: 'Kikuyu, Luo, Kalenjin, Luhya' },
      { label: 'Living Languages', value: '68' },
      { label: 'Business Language', value: 'English' },
    ],
    population: [
      { label: 'Total Population', value: '54.0M' },
      { label: 'Urban Population', value: '28%' },
      { label: 'Median Age', value: '20.1 yrs' },
      { label: 'Population Growth', value: '+1.9%/yr' },
      { label: 'Population Density', value: '94/km²' },
    ],
    economy: [
      { label: 'GDP', value: '$118.1B' },
      { label: 'GDP Growth', value: '+5.4%' },
      { label: 'Key Sectors', value: 'Services 43%, Agriculture 21%, Industry 17%' },
      { label: 'Inflation Rate', value: '6.8%' },
      { label: 'FX Reserves', value: '$7.1B' },
    ],
  },
  tanzania: {
    agriculture: [
      { label: 'Arable Land', value: '14.3%', note: 'of total land area' },
      { label: 'Agriculture Share of GDP', value: '26.1%' },
      { label: 'Workforce in Agriculture', value: '65%' },
      { label: 'Leading Exports', value: 'Cashew nuts, coffee, cotton, tobacco' },
      { label: 'Irrigated Cropland', value: '2.1%' },
    ],
    water: [
      { label: 'Access to Clean Water', value: '61%', note: 'of population' },
      { label: 'Renewable Water Resources', value: '84.0 km³/yr' },
      { label: 'Major Basins', value: 'Lake Victoria, Lake Tanganyika, Rufiji' },
      { label: 'Water Stress Level', value: 'Low–Medium' },
      { label: 'Hydropower Share of Grid', value: '30%' },
    ],
    climate: [
      { label: 'Climate Zone', value: 'Tropical coastal, semi-arid interior' },
      { label: 'Avg. Annual Temperature', value: '25°C (77°F)' },
      { label: 'Annual Rainfall', value: '1,050 mm' },
      { label: 'Dominant Climate Risk', value: 'Flooding, coastal erosion' },
      { label: 'Rainy Seasons', value: 'Mar–May, Nov–Dec' },
    ],
    languages: [
      { label: 'Official Languages', value: 'Swahili, English' },
      { label: 'Widely Spoken', value: 'Sukuma, Chagga, Nyamwezi' },
      { label: 'Living Languages', value: '126' },
      { label: 'Business Language', value: 'Swahili, English' },
    ],
    population: [
      { label: 'Total Population', value: '63.0M' },
      { label: 'Urban Population', value: '36%' },
      { label: 'Median Age', value: '18.0 yrs' },
      { label: 'Population Growth', value: '+3.0%/yr' },
      { label: 'Population Density', value: '67/km²' },
    ],
    economy: [
      { label: 'GDP', value: '$84.0B' },
      { label: 'GDP Growth', value: '+5.1%' },
      { label: 'Key Sectors', value: 'Agriculture 26%, Services 38%, Mining 12%' },
      { label: 'Inflation Rate', value: '3.4%' },
      { label: 'FX Reserves', value: '$5.6B' },
    ],
  },
  nigeria: {
    agriculture: [
      { label: 'Arable Land', value: '37.3%', note: 'of total land area' },
      { label: 'Agriculture Share of GDP', value: '25.2%' },
      { label: 'Workforce in Agriculture', value: '35%' },
      { label: 'Leading Exports', value: 'Cocoa, cassava, sesame, rubber' },
      { label: 'Irrigated Cropland', value: '0.9%', note: 'largely rain-fed smallholder' },
    ],
    water: [
      { label: 'Access to Clean Water', value: '68%', note: 'of population' },
      { label: 'Renewable Water Resources', value: '286.2 km³/yr' },
      { label: 'Major Basins', value: 'Niger River, Lake Chad, Benue' },
      { label: 'Water Stress Level', value: 'Low' },
      { label: 'Hydropower Share of Grid', value: '18%' },
    ],
    climate: [
      { label: 'Climate Zone', value: 'Tropical south, semi-arid north (Sahel)' },
      { label: 'Avg. Annual Temperature', value: '27°C (81°F)' },
      { label: 'Annual Rainfall', value: '1,150 mm', note: 'varies sharply north–south' },
      { label: 'Dominant Climate Risk', value: 'Flooding, desertification (north)' },
      { label: 'Rainy Seasons', value: 'Apr–Oct (south), Jun–Sep (north)' },
    ],
    languages: [
      { label: 'Official Language', value: 'English' },
      { label: 'Widely Spoken', value: 'Hausa, Yoruba, Igbo' },
      { label: 'Living Languages', value: '520+' },
      { label: 'Business Language', value: 'English' },
    ],
    population: [
      { label: 'Total Population', value: '218.5M' },
      { label: 'Urban Population', value: '53%' },
      { label: 'Median Age', value: '18.1 yrs' },
      { label: 'Population Growth', value: '+2.4%/yr' },
      { label: 'Population Density', value: '237/km²' },
    ],
    economy: [
      { label: 'GDP', value: '$477.4B' },
      { label: 'GDP Growth', value: '+3.1%' },
      { label: 'Key Sectors', value: 'Services 52%, Oil & Gas 6%, Agriculture 25%' },
      { label: 'Inflation Rate', value: '28.9%' },
      { label: 'FX Reserves', value: '$32.9B' },
    ],
  },
  ghana: {
    agriculture: [
      { label: 'Arable Land', value: '20.9%', note: 'of total land area' },
      { label: 'Agriculture Share of GDP', value: '19.0%' },
      { label: 'Workforce in Agriculture', value: '30%' },
      { label: 'Leading Exports', value: 'Cocoa, cashew, shea, palm oil' },
      { label: 'Irrigated Cropland', value: '0.5%' },
    ],
    water: [
      { label: 'Access to Clean Water', value: '86%', note: 'of population' },
      { label: 'Renewable Water Resources', value: '53.2 km³/yr' },
      { label: 'Major Basins', value: 'Volta River, Lake Volta' },
      { label: 'Water Stress Level', value: 'Low' },
      { label: 'Hydropower Share of Grid', value: '41%' },
    ],
    climate: [
      { label: 'Climate Zone', value: 'Tropical, savanna north' },
      { label: 'Avg. Annual Temperature', value: '26°C (79°F)' },
      { label: 'Annual Rainfall', value: '1,200 mm' },
      { label: 'Dominant Climate Risk', value: 'Coastal erosion, seasonal flooding' },
      { label: 'Rainy Seasons', value: 'Apr–Jul, Sep–Oct' },
    ],
    languages: [
      { label: 'Official Language', value: 'English' },
      { label: 'Widely Spoken', value: 'Twi, Ewe, Ga, Dagbani' },
      { label: 'Living Languages', value: '81' },
      { label: 'Business Language', value: 'English' },
    ],
    population: [
      { label: 'Total Population', value: '32.4M' },
      { label: 'Urban Population', value: '58%' },
      { label: 'Median Age', value: '21.5 yrs' },
      { label: 'Population Growth', value: '+2.1%/yr' },
      { label: 'Population Density', value: '140/km²' },
    ],
    economy: [
      { label: 'GDP', value: '$76.4B' },
      { label: 'GDP Growth', value: '+2.9%' },
      { label: 'Key Sectors', value: 'Services 46%, Industry 34%, Agriculture 19%' },
      { label: 'Inflation Rate', value: '23.2%' },
      { label: 'FX Reserves', value: '$5.9B' },
    ],
  },
  ethiopia: {
    agriculture: [
      { label: 'Arable Land', value: '15.2%', note: 'of total land area' },
      { label: 'Agriculture Share of GDP', value: '32.7%' },
      { label: 'Workforce in Agriculture', value: '66%' },
      { label: 'Leading Exports', value: 'Coffee, oilseeds, khat, flowers' },
      { label: 'Irrigated Cropland', value: '2.7%' },
    ],
    water: [
      { label: 'Access to Clean Water', value: '55%', note: 'of population' },
      { label: 'Renewable Water Resources', value: '122.0 km³/yr' },
      { label: 'Major Basins', value: 'Blue Nile, Awash, Omo' },
      { label: 'Water Stress Level', value: 'Medium' },
      { label: 'Hydropower Share of Grid', value: '90%', note: 'GERD dam capacity ramping' },
    ],
    climate: [
      { label: 'Climate Zone', value: 'Highland temperate, lowland arid' },
      { label: 'Avg. Annual Temperature', value: '20°C (68°F)', note: 'highland moderation' },
      { label: 'Annual Rainfall', value: '848 mm' },
      { label: 'Dominant Climate Risk', value: 'Drought, highland erosion' },
      { label: 'Rainy Seasons', value: 'Jun–Sep (Kiremt)' },
    ],
    languages: [
      { label: 'Official Language', value: 'Amharic' },
      { label: 'Widely Spoken', value: 'Oromo, Tigrinya, Somali' },
      { label: 'Living Languages', value: '90+' },
      { label: 'Business Language', value: 'Amharic, English' },
    ],
    population: [
      { label: 'Total Population', value: '126.5M' },
      { label: 'Urban Population', value: '22%' },
      { label: 'Median Age', value: '19.5 yrs' },
      { label: 'Population Growth', value: '+2.6%/yr' },
      { label: 'Population Density', value: '115/km²' },
    ],
    economy: [
      { label: 'GDP', value: '$156.1B' },
      { label: 'GDP Growth', value: '+6.1%' },
      { label: 'Key Sectors', value: 'Agriculture 33%, Services 40%, Industry 27%' },
      { label: 'Inflation Rate', value: '19.9%' },
      { label: 'FX Reserves', value: '$1.4B' },
    ],
  },
  rwanda: {
    agriculture: [
      { label: 'Arable Land', value: '47.4%', note: 'of total land area' },
      { label: 'Agriculture Share of GDP', value: '24.0%' },
      { label: 'Workforce in Agriculture', value: '58%' },
      { label: 'Leading Exports', value: 'Coffee, tea, minerals, horticulture' },
      { label: 'Irrigated Cropland', value: '1.8%', note: 'terraced hillside farming' },
    ],
    water: [
      { label: 'Access to Clean Water', value: '76%', note: 'of population' },
      { label: 'Renewable Water Resources', value: '5.2 km³/yr' },
      { label: 'Major Basins', value: 'Lake Kivu, Nyabarongo River' },
      { label: 'Water Stress Level', value: 'Medium' },
      { label: 'Hydropower Share of Grid', value: '48%' },
    ],
    climate: [
      { label: 'Climate Zone', value: 'Temperate highland ("Land of a Thousand Hills")' },
      { label: 'Avg. Annual Temperature', value: '19°C (66°F)' },
      { label: 'Annual Rainfall', value: '1,150 mm' },
      { label: 'Dominant Climate Risk', value: 'Landslides, hillside soil erosion' },
      { label: 'Rainy Seasons', value: 'Mar–May, Oct–Dec' },
    ],
    languages: [
      { label: 'Official Languages', value: 'Kinyarwanda, English, French' },
      { label: 'Widely Spoken', value: 'Kinyarwanda (near-universal)' },
      { label: 'Living Languages', value: '4' },
      { label: 'Business Language', value: 'English' },
    ],
    population: [
      { label: 'Total Population', value: '13.9M' },
      { label: 'Urban Population', value: '18%' },
      { label: 'Median Age', value: '20.0 yrs' },
      { label: 'Population Growth', value: '+2.3%/yr' },
      { label: 'Population Density', value: '525/km²', note: 'highest in mainland Africa' },
    ],
    economy: [
      { label: 'GDP', value: '$13.3B' },
      { label: 'GDP Growth', value: '+8.2%' },
      { label: 'Key Sectors', value: 'Services 48%, Agriculture 24%, Industry 20%' },
      { label: 'Inflation Rate', value: '4.9%' },
      { label: 'FX Reserves', value: '$1.9B' },
    ],
  },
  uganda: {
    agriculture: [
      { label: 'Arable Land', value: '34.0%', note: 'of total land area' },
      { label: 'Agriculture Share of GDP', value: '23.7%' },
      { label: 'Workforce in Agriculture', value: '62%' },
      { label: 'Leading Exports', value: 'Coffee, tea, fish, tobacco' },
      { label: 'Irrigated Cropland', value: '0.2%' },
    ],
    water: [
      { label: 'Access to Clean Water', value: '65%', note: 'of population' },
      { label: 'Renewable Water Resources', value: '39.0 km³/yr' },
      { label: 'Major Basins', value: 'Lake Victoria, Lake Albert, Nile source' },
      { label: 'Water Stress Level', value: 'Low' },
      { label: 'Hydropower Share of Grid', value: '77%' },
    ],
    climate: [
      { label: 'Climate Zone', value: 'Tropical, moderated by altitude' },
      { label: 'Avg. Annual Temperature', value: '22°C (72°F)' },
      { label: 'Annual Rainfall', value: '1,300 mm' },
      { label: 'Dominant Climate Risk', value: 'Flooding, landslides in east' },
      { label: 'Rainy Seasons', value: 'Mar–May, Sep–Nov' },
    ],
    languages: [
      { label: 'Official Languages', value: 'English, Swahili' },
      { label: 'Widely Spoken', value: 'Luganda, Runyankole, Luo' },
      { label: 'Living Languages', value: '43' },
      { label: 'Business Language', value: 'English' },
    ],
    population: [
      { label: 'Total Population', value: '48.6M' },
      { label: 'Urban Population', value: '26%' },
      { label: 'Median Age', value: '16.7 yrs', note: 'one of world\'s youngest' },
      { label: 'Population Growth', value: '+3.0%/yr' },
      { label: 'Population Density', value: '253/km²' },
    ],
    economy: [
      { label: 'GDP', value: '$49.3B' },
      { label: 'GDP Growth', value: '+5.7%' },
      { label: 'Key Sectors', value: 'Services 45%, Agriculture 24%, Industry 26%' },
      { label: 'Inflation Rate', value: '3.5%' },
      { label: 'FX Reserves', value: '$3.4B' },
    ],
  },
  zimbabwe: {
    agriculture: [
      { label: 'Arable Land', value: '10.5%', note: 'of total land area' },
      { label: 'Agriculture Share of GDP', value: '17.3%' },
      { label: 'Workforce in Agriculture', value: '60%' },
      { label: 'Leading Exports', value: 'Tobacco, cotton, horticulture, maize' },
      { label: 'Irrigated Cropland', value: '3.1%' },
    ],
    water: [
      { label: 'Access to Clean Water', value: '68%', note: 'of population' },
      { label: 'Renewable Water Resources', value: '12.3 km³/yr' },
      { label: 'Major Basins', value: 'Zambezi River, Lake Kariba' },
      { label: 'Water Stress Level', value: 'Medium' },
      { label: 'Hydropower Share of Grid', value: '54%', note: 'Kariba Dam dependency' },
    ],
    climate: [
      { label: 'Climate Zone', value: 'Subtropical highveld, semi-arid lowveld' },
      { label: 'Avg. Annual Temperature', value: '21°C (70°F)' },
      { label: 'Annual Rainfall', value: '675 mm' },
      { label: 'Dominant Climate Risk', value: 'Recurrent drought, El Niño exposure' },
      { label: 'Rainy Season', value: 'Nov–Mar' },
    ],
    languages: [
      { label: 'Official Languages', value: 'English, Shona, Ndebele (+13 recognized)' },
      { label: 'Widely Spoken', value: 'Shona, Ndebele' },
      { label: 'Living Languages', value: '16' },
      { label: 'Business Language', value: 'English' },
    ],
    population: [
      { label: 'Total Population', value: '16.7M' },
      { label: 'Urban Population', value: '32%' },
      { label: 'Median Age', value: '19.8 yrs' },
      { label: 'Population Growth', value: '+1.5%/yr' },
      { label: 'Population Density', value: '43/km²' },
    ],
    economy: [
      { label: 'GDP', value: '$26.7B' },
      { label: 'GDP Growth', value: '+3.4%' },
      { label: 'Key Sectors', value: 'Services 51%, Agriculture 17%, Mining 12%' },
      { label: 'Inflation Rate', value: '55.6%', note: 'ZiG currency stabilization ongoing' },
      { label: 'FX Reserves', value: '$0.5B' },
    ],
  },
  'south-africa': {
    agriculture: [
      { label: 'Arable Land', value: '10.3%', note: 'of total land area' },
      { label: 'Agriculture Share of GDP', value: '2.5%' },
      { label: 'Workforce in Agriculture', value: '5.5%' },
      { label: 'Leading Exports', value: 'Citrus, wine, maize, wool' },
      { label: 'Irrigated Cropland', value: '9.5%' },
    ],
    water: [
      { label: 'Access to Clean Water', value: '90%', note: 'of population' },
      { label: 'Renewable Water Resources', value: '51.4 km³/yr' },
      { label: 'Major Basins', value: 'Orange River, Vaal, Limpopo' },
      { label: 'Water Stress Level', value: 'High' },
      { label: 'Hydropower Share of Grid', value: '4%' },
    ],
    climate: [
      { label: 'Climate Zone', value: 'Semi-arid, Mediterranean (Western Cape)' },
      { label: 'Avg. Annual Temperature', value: '18°C (64°F)' },
      { label: 'Annual Rainfall', value: '495 mm' },
      { label: 'Dominant Climate Risk', value: 'Drought, Cape Town water crisis legacy' },
      { label: 'Rainy Season', value: 'Oct–Mar (east), May–Aug (Western Cape)' },
    ],
    languages: [
      { label: 'Official Languages', value: '12 official (incl. isiZulu, English, Afrikaans)' },
      { label: 'Widely Spoken', value: 'isiZulu, isiXhosa, Afrikaans' },
      { label: 'Living Languages', value: '35+' },
      { label: 'Business Language', value: 'English' },
    ],
    population: [
      { label: 'Total Population', value: '60.4M' },
      { label: 'Urban Population', value: '68%' },
      { label: 'Median Age', value: '28.0 yrs' },
      { label: 'Population Growth', value: '+0.8%/yr' },
      { label: 'Population Density', value: '49/km²' },
    ],
    economy: [
      { label: 'GDP', value: '$403.0B' },
      { label: 'GDP Growth', value: '+1.1%' },
      { label: 'Key Sectors', value: 'Services 65%, Industry 26%, Agriculture 2.5%' },
      { label: 'Inflation Rate', value: '5.1%' },
      { label: 'FX Reserves', value: '$62.6B' },
    ],
  },
  zambia: {
    agriculture: [
      { label: 'Arable Land', value: '4.8%', note: 'of total land area' },
      { label: 'Agriculture Share of GDP', value: '9.6%' },
      { label: 'Workforce in Agriculture', value: '48%' },
      { label: 'Leading Exports', value: 'Maize, soybeans, sugar, tobacco' },
      { label: 'Irrigated Cropland', value: '1.6%' },
    ],
    water: [
      { label: 'Access to Clean Water', value: '67%', note: 'of population' },
      { label: 'Renewable Water Resources', value: '105.2 km³/yr' },
      { label: 'Major Basins', value: 'Zambezi River, Lake Kariba' },
      { label: 'Water Stress Level', value: 'Low' },
      { label: 'Hydropower Share of Grid', value: '83%', note: 'Kariba drought exposure' },
    ],
    climate: [
      { label: 'Climate Zone', value: 'Tropical plateau, moderated by altitude' },
      { label: 'Avg. Annual Temperature', value: '21°C (70°F)' },
      { label: 'Annual Rainfall', value: '1,020 mm' },
      { label: 'Dominant Climate Risk', value: 'Drought cycles, Kariba water level decline' },
      { label: 'Rainy Season', value: 'Nov–Apr' },
    ],
    languages: [
      { label: 'Official Language', value: 'English' },
      { label: 'Widely Spoken', value: 'Bemba, Nyanja, Tonga' },
      { label: 'Living Languages', value: '43' },
      { label: 'Business Language', value: 'English' },
    ],
    population: [
      { label: 'Total Population', value: '20.6M' },
      { label: 'Urban Population', value: '45%' },
      { label: 'Median Age', value: '17.7 yrs' },
      { label: 'Population Growth', value: '+2.8%/yr' },
      { label: 'Population Density', value: '27/km²' },
    ],
    economy: [
      { label: 'GDP', value: '$28.2B' },
      { label: 'GDP Growth', value: '+4.7%' },
      { label: 'Key Sectors', value: 'Services 45%, Mining 15%, Agriculture 10%' },
      { label: 'Inflation Rate', value: '15.7%' },
      { label: 'FX Reserves', value: '$3.5B' },
    ],
  },
  botswana: {
    agriculture: [
      { label: 'Arable Land', value: '0.5%', note: 'of total land area' },
      { label: 'Agriculture Share of GDP', value: '1.8%' },
      { label: 'Workforce in Agriculture', value: '17%' },
      { label: 'Leading Exports', value: 'Beef, sorghum, cotton' },
      { label: 'Irrigated Cropland', value: '0.4%' },
    ],
    water: [
      { label: 'Access to Clean Water', value: '90%', note: 'of population' },
      { label: 'Renewable Water Resources', value: '14.7 km³/yr' },
      { label: 'Major Basins', value: 'Okavango Delta, Limpopo' },
      { label: 'Water Stress Level', value: 'High', note: 'largely arid Kalahari terrain' },
      { label: 'Hydropower Share of Grid', value: '<1%' },
    ],
    climate: [
      { label: 'Climate Zone', value: 'Semi-arid, Kalahari desert interior' },
      { label: 'Avg. Annual Temperature', value: '21°C (70°F)' },
      { label: 'Annual Rainfall', value: '400 mm' },
      { label: 'Dominant Climate Risk', value: 'Recurrent drought' },
      { label: 'Rainy Season', value: 'Nov–Mar' },
    ],
    languages: [
      { label: 'Official Language', value: 'English' },
      { label: 'Widely Spoken', value: 'Setswana (near-universal)' },
      { label: 'Living Languages', value: '28' },
      { label: 'Business Language', value: 'English' },
    ],
    population: [
      { label: 'Total Population', value: '2.5M' },
      { label: 'Urban Population', value: '73%' },
      { label: 'Median Age', value: '25.3 yrs' },
      { label: 'Population Growth', value: '+1.5%/yr' },
      { label: 'Population Density', value: '4.4/km²', note: 'one of Africa\'s lowest' },
    ],
    economy: [
      { label: 'GDP', value: '$20.4B' },
      { label: 'GDP Growth', value: '+1.6%' },
      { label: 'Key Sectors', value: 'Mining 25%, Services 60%, Agriculture 2%' },
      { label: 'Inflation Rate', value: '3.5%' },
      { label: 'FX Reserves', value: '$4.6B' },
    ],
  },
  namibia: {
    agriculture: [
      { label: 'Arable Land', value: '1.0%', note: 'of total land area' },
      { label: 'Agriculture Share of GDP', value: '8.9%' },
      { label: 'Workforce in Agriculture', value: '24%' },
      { label: 'Leading Exports', value: 'Beef, grapes, fish, livestock' },
      { label: 'Irrigated Cropland', value: '0.7%' },
    ],
    water: [
      { label: 'Access to Clean Water', value: '84%', note: 'of population' },
      { label: 'Renewable Water Resources', value: '9.9 km³/yr' },
      { label: 'Major Basins', value: 'Orange River, Kunene, Okavango' },
      { label: 'Water Stress Level', value: 'Very High', note: 'driest country in Sub-Saharan Africa' },
      { label: 'Hydropower Share of Grid', value: '35%', note: 'Ruacana plant' },
    ],
    climate: [
      { label: 'Climate Zone', value: 'Arid to semi-arid, Namib and Kalahari deserts' },
      { label: 'Avg. Annual Temperature', value: '20°C (68°F)' },
      { label: 'Annual Rainfall', value: '270 mm' },
      { label: 'Dominant Climate Risk', value: 'Severe drought, water scarcity' },
      { label: 'Rainy Season', value: 'Oct–Apr' },
    ],
    languages: [
      { label: 'Official Language', value: 'English' },
      { label: 'Widely Spoken', value: 'Oshiwambo, Afrikaans, Nama' },
      { label: 'Living Languages', value: '30' },
      { label: 'Business Language', value: 'English' },
    ],
    population: [
      { label: 'Total Population', value: '3.0M' },
      { label: 'Urban Population', value: '55%' },
      { label: 'Median Age', value: '21.4 yrs' },
      { label: 'Population Growth', value: '+1.6%/yr' },
      { label: 'Population Density', value: '3.6/km²', note: 'among world\'s lowest' },
    ],
    economy: [
      { label: 'GDP', value: '$12.8B' },
      { label: 'GDP Growth', value: '+3.7%' },
      { label: 'Key Sectors', value: 'Services 58%, Mining 12%, Agriculture 9%' },
      { label: 'Inflation Rate', value: '4.5%' },
      { label: 'FX Reserves', value: '$2.4B' },
    ],
  },
  mozambique: {
    agriculture: [
      { label: 'Arable Land', value: '10.6%', note: 'of total land area' },
      { label: 'Agriculture Share of GDP', value: '22.1%' },
      { label: 'Workforce in Agriculture', value: '70%' },
      { label: 'Leading Exports', value: 'Cashew nuts, cotton, sugar, tobacco' },
      { label: 'Irrigated Cropland', value: '2.9%' },
    ],
    water: [
      { label: 'Access to Clean Water', value: '58%', note: 'of population' },
      { label: 'Renewable Water Resources', value: '100.6 km³/yr' },
      { label: 'Major Basins', value: 'Zambezi, Limpopo, Save' },
      { label: 'Water Stress Level', value: 'Low' },
      { label: 'Hydropower Share of Grid', value: '78%', note: 'Cahora Bassa dam' },
    ],
    climate: [
      { label: 'Climate Zone', value: 'Tropical coastal, savanna interior' },
      { label: 'Avg. Annual Temperature', value: '24°C (75°F)' },
      { label: 'Annual Rainfall', value: '1,032 mm' },
      { label: 'Dominant Climate Risk', value: 'Cyclones, coastal flooding' },
      { label: 'Rainy Season', value: 'Nov–Mar' },
    ],
    languages: [
      { label: 'Official Language', value: 'Portuguese' },
      { label: 'Widely Spoken', value: 'Makhuwa, Sena, Ndau' },
      { label: 'Living Languages', value: '43' },
      { label: 'Business Language', value: 'Portuguese' },
    ],
    population: [
      { label: 'Total Population', value: '34.6M' },
      { label: 'Urban Population', value: '39%' },
      { label: 'Median Age', value: '17.6 yrs' },
      { label: 'Population Growth', value: '+2.9%/yr' },
      { label: 'Population Density', value: '44/km²' },
    ],
    economy: [
      { label: 'GDP', value: '$21.2B' },
      { label: 'GDP Growth', value: '+4.0%' },
      { label: 'Key Sectors', value: 'Services 44%, Agriculture 22%, Industry 22%' },
      { label: 'Inflation Rate', value: '5.3%' },
      { label: 'FX Reserves', value: '$3.1B' },
    ],
  },
  angola: {
    agriculture: [
      { label: 'Arable Land', value: '4.4%', note: 'of total land area' },
      { label: 'Agriculture Share of GDP', value: '7.6%' },
      { label: 'Workforce in Agriculture', value: '43%' },
      { label: 'Leading Exports', value: 'Coffee, cassava, bananas, sisal' },
      { label: 'Irrigated Cropland', value: '0.8%' },
    ],
    water: [
      { label: 'Access to Clean Water', value: '58%', note: 'of population' },
      { label: 'Renewable Water Resources', value: '184.0 km³/yr' },
      { label: 'Major Basins', value: 'Congo, Cuanza, Cunene' },
      { label: 'Water Stress Level', value: 'Low' },
      { label: 'Hydropower Share of Grid', value: '65%', note: 'Laúca and Cambambe dams' },
    ],
    climate: [
      { label: 'Climate Zone', value: 'Tropical coastal, semi-arid south' },
      { label: 'Avg. Annual Temperature', value: '22°C (72°F)' },
      { label: 'Annual Rainfall', value: '1,010 mm' },
      { label: 'Dominant Climate Risk', value: 'Drought (south), coastal flooding' },
      { label: 'Rainy Season', value: 'Oct–Apr' },
    ],
    languages: [
      { label: 'Official Language', value: 'Portuguese' },
      { label: 'Widely Spoken', value: 'Umbundu, Kimbundu, Kikongo' },
      { label: 'Living Languages', value: '41' },
      { label: 'Business Language', value: 'Portuguese' },
    ],
    population: [
      { label: 'Total Population', value: '36.7M' },
      { label: 'Urban Population', value: '68%' },
      { label: 'Median Age', value: '16.7 yrs' },
      { label: 'Population Growth', value: '+3.3%/yr' },
      { label: 'Population Density', value: '29/km²' },
    ],
    economy: [
      { label: 'GDP', value: '$92.0B' },
      { label: 'GDP Growth', value: '+2.6%' },
      { label: 'Key Sectors', value: 'Oil & Gas 30%, Services 40%, Agriculture 8%' },
      { label: 'Inflation Rate', value: '19.6%' },
      { label: 'FX Reserves', value: '$14.8B' },
    ],
  },
  malawi: {
    agriculture: [
      { label: 'Arable Land', value: '37.3%', note: 'of total land area' },
      { label: 'Agriculture Share of GDP', value: '22.4%' },
      { label: 'Workforce in Agriculture', value: '64%' },
      { label: 'Leading Exports', value: 'Tobacco, tea, sugar, macadamia' },
      { label: 'Irrigated Cropland', value: '2.5%' },
    ],
    water: [
      { label: 'Access to Clean Water', value: '71%', note: 'of population' },
      { label: 'Renewable Water Resources', value: '17.3 km³/yr' },
      { label: 'Major Basins', value: 'Lake Malawi, Shire River' },
      { label: 'Water Stress Level', value: 'Medium' },
      { label: 'Hydropower Share of Grid', value: '80%', note: 'Shire River cascade' },
    ],
    climate: [
      { label: 'Climate Zone', value: 'Subtropical highland' },
      { label: 'Avg. Annual Temperature', value: '22°C (72°F)' },
      { label: 'Annual Rainfall', value: '1,180 mm' },
      { label: 'Dominant Climate Risk', value: 'Cyclones (Freddy 2023), drought' },
      { label: 'Rainy Season', value: 'Nov–Apr' },
    ],
    languages: [
      { label: 'Official Language', value: 'English' },
      { label: 'Widely Spoken', value: 'Chichewa (near-universal)' },
      { label: 'Living Languages', value: '15' },
      { label: 'Business Language', value: 'English' },
    ],
    population: [
      { label: 'Total Population', value: '21.2M' },
      { label: 'Urban Population', value: '18%' },
      { label: 'Median Age', value: '17.9 yrs' },
      { label: 'Population Growth', value: '+2.6%/yr' },
      { label: 'Population Density', value: '179/km²' },
    ],
    economy: [
      { label: 'GDP', value: '$13.1B' },
      { label: 'GDP Growth', value: '+1.8%' },
      { label: 'Key Sectors', value: 'Agriculture 22%, Services 51%, Industry 19%' },
      { label: 'Inflation Rate', value: '28.8%', note: 'post-devaluation pass-through' },
      { label: 'FX Reserves', value: '$0.3B' },
    ],
  },
  lesotho: {
    agriculture: [
      { label: 'Arable Land', value: '10.0%', note: 'of total land area' },
      { label: 'Agriculture Share of GDP', value: '5.4%' },
      { label: 'Workforce in Agriculture', value: '33%' },
      { label: 'Leading Exports', value: 'Wool, mohair, vegetables' },
      { label: 'Irrigated Cropland', value: '0.3%' },
    ],
    water: [
      { label: 'Access to Clean Water', value: '78%', note: 'of population' },
      { label: 'Renewable Water Resources', value: '5.2 km³/yr' },
      { label: 'Major Basins', value: 'Orange (Senqu) River headwaters' },
      { label: 'Water Stress Level', value: 'Low', note: 'net water exporter via Highlands Project' },
      { label: 'Hydropower Share of Grid', value: '65%', note: '\'Muela hydropower station' },
    ],
    climate: [
      { label: 'Climate Zone', value: 'Highland temperate, alpine peaks' },
      { label: 'Avg. Annual Temperature', value: '13°C (55°F)', note: 'coldest capital in Africa' },
      { label: 'Annual Rainfall', value: '760 mm' },
      { label: 'Dominant Climate Risk', value: 'Snow/frost damage, soil erosion' },
      { label: 'Rainy Season', value: 'Oct–Apr' },
    ],
    languages: [
      { label: 'Official Languages', value: 'Sesotho, English' },
      { label: 'Widely Spoken', value: 'Sesotho (near-universal)' },
      { label: 'Living Languages', value: '4' },
      { label: 'Business Language', value: 'English' },
    ],
    population: [
      { label: 'Total Population', value: '2.3M' },
      { label: 'Urban Population', value: '29%' },
      { label: 'Median Age', value: '24.4 yrs' },
      { label: 'Population Growth', value: '+0.3%/yr' },
      { label: 'Population Density', value: '76/km²' },
    ],
    economy: [
      { label: 'GDP', value: '$2.3B' },
      { label: 'GDP Growth', value: '+2.3%' },
      { label: 'Key Sectors', value: 'Services 46%, Industry 34% (textiles), Agriculture 5%' },
      { label: 'Inflation Rate', value: '6.1%' },
      { label: 'FX Reserves', value: '$0.6B' },
    ],
  },
  eswatini: {
    agriculture: [
      { label: 'Arable Land', value: '9.9%', note: 'of total land area' },
      { label: 'Agriculture Share of GDP', value: '6.8%' },
      { label: 'Workforce in Agriculture', value: '11%' },
      { label: 'Leading Exports', value: 'Sugar, soft drink concentrate, wood pulp' },
      { label: 'Irrigated Cropland', value: '5.2%', note: 'high for sugarcane estates' },
    ],
    water: [
      { label: 'Access to Clean Water', value: '75%', note: 'of population' },
      { label: 'Renewable Water Resources', value: '4.5 km³/yr' },
      { label: 'Major Basins', value: 'Komati, Usutu (Great Usuthu) rivers' },
      { label: 'Water Stress Level', value: 'Medium' },
      { label: 'Hydropower Share of Grid', value: '30%' },
    ],
    climate: [
      { label: 'Climate Zone', value: 'Temperate highveld, subtropical lowveld' },
      { label: 'Avg. Annual Temperature', value: '19°C (66°F)' },
      { label: 'Annual Rainfall', value: '790 mm' },
      { label: 'Dominant Climate Risk', value: 'Drought, lowveld heat stress' },
      { label: 'Rainy Season', value: 'Oct–Mar' },
    ],
    languages: [
      { label: 'Official Languages', value: 'siSwati, English' },
      { label: 'Widely Spoken', value: 'siSwati (near-universal)' },
      { label: 'Living Languages', value: '4' },
      { label: 'Business Language', value: 'English' },
    ],
    population: [
      { label: 'Total Population', value: '1.2M' },
      { label: 'Urban Population', value: '24%' },
      { label: 'Median Age', value: '21.4 yrs' },
      { label: 'Population Growth', value: '+0.9%/yr' },
      { label: 'Population Density', value: '69/km²' },
    ],
    economy: [
      { label: 'GDP', value: '$4.7B' },
      { label: 'GDP Growth', value: '+4.7%' },
      { label: 'Key Sectors', value: 'Manufacturing 32%, Services 47%, Agriculture 7%' },
      { label: 'Inflation Rate', value: '4.4%' },
      { label: 'FX Reserves', value: '$0.6B' },
    ],
  },
  madagascar: {
    agriculture: [
      { label: 'Arable Land', value: '6.0%', note: 'of total land area' },
      { label: 'Agriculture Share of GDP', value: '22.3%' },
      { label: 'Workforce in Agriculture', value: '69%' },
      { label: 'Leading Exports', value: 'Vanilla, cloves, litchi, cocoa' },
      { label: 'Irrigated Cropland', value: '32%', note: 'extensive rice paddy irrigation' },
    ],
    water: [
      { label: 'Access to Clean Water', value: '56%', note: 'of population' },
      { label: 'Renewable Water Resources', value: '337.0 km³/yr' },
      { label: 'Major Basins', value: 'Betsiboka, Mangoky rivers' },
      { label: 'Water Stress Level', value: 'Low' },
      { label: 'Hydropower Share of Grid', value: '55%' },
    ],
    climate: [
      { label: 'Climate Zone', value: 'Tropical east, arid southwest' },
      { label: 'Avg. Annual Temperature', value: '23°C (73°F)' },
      { label: 'Annual Rainfall', value: '1,513 mm', note: 'high east-west variation' },
      { label: 'Dominant Climate Risk', value: 'Cyclones, southern drought' },
      { label: 'Rainy Season', value: 'Nov–Apr' },
    ],
    languages: [
      { label: 'Official Languages', value: 'Malagasy, French' },
      { label: 'Widely Spoken', value: 'Malagasy (near-universal)' },
      { label: 'Living Languages', value: '17' },
      { label: 'Business Language', value: 'French' },
    ],
    population: [
      { label: 'Total Population', value: '30.3M' },
      { label: 'Urban Population', value: '39%' },
      { label: 'Median Age', value: '19.9 yrs' },
      { label: 'Population Growth', value: '+2.3%/yr' },
      { label: 'Population Density', value: '52/km²' },
    ],
    economy: [
      { label: 'GDP', value: '$16.9B' },
      { label: 'GDP Growth', value: '+4.5%' },
      { label: 'Key Sectors', value: 'Agriculture 22%, Services 54%, Industry 24%' },
      { label: 'Inflation Rate', value: '8.6%' },
      { label: 'FX Reserves', value: '$3.4B' },
    ],
  },
  mauritius: {
    agriculture: [
      { label: 'Arable Land', value: '38.2%', note: 'of total land area' },
      { label: 'Agriculture Share of GDP', value: '3.1%' },
      { label: 'Workforce in Agriculture', value: '5.6%' },
      { label: 'Leading Exports', value: 'Sugar, processed fish, textiles' },
      { label: 'Irrigated Cropland', value: '19%' },
    ],
    water: [
      { label: 'Access to Clean Water', value: '100%', note: 'of population' },
      { label: 'Renewable Water Resources', value: '2.2 km³/yr' },
      { label: 'Major Basins', value: 'Grand River South East, Rivière du Rempart' },
      { label: 'Water Stress Level', value: 'Medium' },
      { label: 'Hydropower Share of Grid', value: '5%' },
    ],
    climate: [
      { label: 'Climate Zone', value: 'Tropical maritime, small island' },
      { label: 'Avg. Annual Temperature', value: '24°C (75°F)' },
      { label: 'Annual Rainfall', value: '2,100 mm' },
      { label: 'Dominant Climate Risk', value: 'Cyclones, coastal erosion, sea-level rise' },
      { label: 'Rainy Season', value: 'Nov–Apr' },
    ],
    languages: [
      { label: 'Official Language', value: 'English' },
      { label: 'Widely Spoken', value: 'Mauritian Creole, French' },
      { label: 'Living Languages', value: '9' },
      { label: 'Business Language', value: 'English, French' },
    ],
    population: [
      { label: 'Total Population', value: '1.3M' },
      { label: 'Urban Population', value: '41%' },
      { label: 'Median Age', value: '38.0 yrs' },
      { label: 'Population Growth', value: '+0.1%/yr' },
      { label: 'Population Density', value: '638/km²', note: 'among Africa\'s highest' },
    ],
    economy: [
      { label: 'GDP', value: '$16.6B' },
      { label: 'GDP Growth', value: '+5.0%' },
      { label: 'Key Sectors', value: 'Services 76%, Industry 20%, Agriculture 3%' },
      { label: 'Inflation Rate', value: '3.9%' },
      { label: 'FX Reserves', value: '$8.5B' },
    ],
  },
};
